### PR TITLE
Feat/add support for dotnet8

### LINKED ISSUE #1250: [CLI] - Add support for .NET 8
Waiting for stable release of .NET 8.

(Similar to https://github.com/dotnet/roslynator/issues/979)

### PR DESCRIPTION
**Pull request by JonasSchubert**
fixes #1250

### CODE REVIEW

**Comment by JonasSchubert** [comment]
@dotnet-policy-service agree

**Comment by josefpihrt** [comment]
Blocked by https://github.com/actions/runner-images/pull/8819

**Review by josefpihrt — CHANGES_REQUESTED** [review]
Hi,

Thanks for the PR, looks good, just please update changelog.

**Comment by JonasSchubert** [comment]
> Hi,
> 
> Thanks for the PR, looks good, just please update changelog.

Hi @josefpihrt,
Thanks for the quick workflow update. I added a note to the changelog as requested.

**Review by josefpihrt — DISMISSED** [review]

**Review by josefpihrt — APPROVED** [review]

**Pull request merged**
